### ISSUE TITLE
Double check

### ISSUE THREAD

**Issue by MacMat01** [MacMat01/MunicipalDigitalization#10]
- [ ] Check consistencies of all the project and if it is synchronized with the Visual Paradigm diagrams
- [ ] #16

**Comment by MacMat01** [comment]
Added some new classes and rearrangements from the Visual Paradigm diagram 

- a21b1e57762067aa269717fb248ac54417254be2 
- 0325d8810fe822ca96dbeae276e46ca5b3c292d5
- a7dfd563ef0ac5ae70652a5bc5dd6d236fa05e60

**Comment by AlfoAnto02** [comment]
Few changes of adjustment
f4240cfb2f64e6cdea6432b0fad70e4013409fc2
1c2a572ea6d63070a761400eb96de4dcd017de72

**Comment by SenseiBonsai2K** [comment]
I got my job DONE!

**Comment by MacMat01** [comment]
Reopened for Iteration 3

**Comment by MacMat01** [comment]
Iteration 3 check closed

- 7739f2c77ff90e779dcf0cdf4297666da0338d15
