### ISSUE TITLE
Create MunicipalElements abstract class and the relative interface

### ISSUE THREAD

**Issue by MacMat01** [MacMat01/MunicipalDigitalization#17]
- [x] Create MunicipalsElements abstract class
- [x] Create IMunicipalElements interface
- [x] #18 @SenseiBonsai2K

**Comment by AlfoAnto02** [comment]
67d529a81629c3b8cfbbfe596785e6ca746349a8 Commit of the abstraction and creation of the Municipal Elements

**Comment by AlfoAnto02** [comment]
87b99251cb1b4e64ef444754632a51f5b54e4697 Commit of the adjustment of the IPOI IItinerary and AbstractPOI

**Comment by AlfoAnto02** [comment]
bd17ca054b870bb9d97b4ffe79d5f53a2c853f4e Commit of the Adjustment to the AbstractItinerary class

**Comment by MacMat01** [comment]
Reopened as there is still one task to be completed
