### ISSUE TITLE
create Content classes Hierarchy

### ISSUE THREAD

**Issue by MacMat01** [MacMat01/MunicipalDigitalization#3]
- [x] Create the Content classes Hierarchy to match the Visual Paradigm diagram
- [x] Update the repository with a push
- [x] #12

**Comment by MacMat01** [comment]
Created Content classes Hierarchy and updated the repository

- 938e34eab2e71dd894307ad82992e97f1da664d3

**Comment by MacMat01** [comment]
Also updated the repository

**Comment by SenseiBonsai2K** [comment]
I got my job DONE!
