### ISSUE TITLE
create checkItineraryControl

### ISSUE THREAD

**Issue by AlfoAnto02** [MacMat01/MunicipalDigitalization#31]
Nella classe UploadingService implementare il metodo checkItinerary. L'implementazione è già eseguita nella classi PendingItineraryBuilder e AuthorizedItineraryBuilder. Quello che bisogna fare è spostare le implementazioni di controllo dei metodi all'interno di checkItinerary in modo da dividere le responsabilità tra Builder e Service.

**Comment by MacMat01** [comment]
checkItinerary method implemented but poiSetCoordinates check to be within municipality coordinates needs to be done.

- ed7ac6ee9b389b8f82ed1365a7619844d85fa4a8

**Comment by MacMat01** [comment]
checkCoordinate implemented:

- e00c6b1c2fe5b58655ba426702bf1622d626288d
