### ISSUE TITLE
create checkPOIControl

### ISSUE THREAD

**Issue by AlfoAnto02** [MacMat01/MunicipalDigitalization#32]
Nella classe UploadingService implementare il metodo checkPOI. L'implementazione è già eseguita nella classi PendingPOIBuilder e AuthorizedPOIBuilder. Quello che bisogna fare è spostare le implementazioni di controllo dei metodi all'interno di checkIPOI in modo da dividere le responsabilità tra Builder e Service.

**Comment by MacMat01** [comment]
checkPOI method implemented but poiSetCoordinates check to be within municipality coordinates needs to be done.

- 04a133796446b59b22f5bf7d71a257284dfe1ce1

**Comment by MacMat01** [comment]
checkCoordinate implemented:

- e00c6b1c2fe5b58655ba426702bf1622d626288d
