### ISSUE TITLE
create checkContent

### ISSUE THREAD

**Issue by AlfoAnto02** [MacMat01/MunicipalDigitalization#33]
Nella classe UploadingService implementare il metodo checkContent. L'implementazione è già eseguita nella classi PendingContentBuilder e AuthorizedContentBuilder. Quello che bisogna fare è spostare le implementazioni di controllo dei metodi all'interno di checkContent in modo da dividere le responsabilità tra Builder e Service.

**Comment by MacMat01** [comment]
checkContent method implemented.

- ca1f2c4500af8b02baf4523a533cff8850d1f556
