### ISSUE TITLE
create ContentController

### ISSUE THREAD

**Issue by MacMat01** [MacMat01/MunicipalDigitalization#4]
- [x] Create the ContentController class to match the Visual Paradigm diagram
- [x] #11

**Comment by MacMat01** [comment]
ContentController class created and synchronized

- 938e34eab2e71dd894307ad82992e97f1da664d3

**Comment by MacMat01** [comment]
ContentController and interface implemented

- 1a23d64eaac79ccd20b9c08c4b7ba2c45a126e4b

**Comment by SenseiBonsai2K** [comment]
I got my job DONE!
